[package]
name = "oscillatory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.9.1"
egui = "0.20.1"
bevy_egui = "0.19.0"
